Code editor: selecting a part of a word raises an IndexError exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\widgets\sourcecode\codeeditor.py", line 932, in __mark_occurences
    self.occurences.pop(-1)
IndexError: pop from empty list

Update Issue 973
Status: Fixed

This was due to a difference of behavior between PyQt4 and PySide for the
QTextDocument.find function used in the occurence highlighting feature.
This is just a workaround.