pyside: Fix preferences modified by checkboxes
Saving/changing preferences modified by checkboxes in the Preferences
dialog fails with the following error:

TypeError: <lambda>() missing 1 required positional argument: '_'

Apparently, PyQt and PySide behave differently when a signal is
connected with a slot. This is influenced by various factors
(overloading, optional argument in signal’s C++ interface, type of slot
[lamda or conventional function], number of arguments in slot, presence
of optional arguments in slot…). See e.g. [1][2].

Explicitly select the correct signal type.

[1] https://codereview.qt-project.org/c/pyside/pyside-setup/+/220083
[2] https://bugreports.qt.io/browse/PYSIDE-909