Fixed regression (see revision 027f4486ce4a): impossible to import InternalShell from an external module (importing spyderlib/spyder.py inside the internal shell widget module is a bad idea)
The statement "from spyderlib.widgets.internalshell import InternalShell" when
executed from an external script (i.e. outside spyderlib) was generating the
following traceback:

  File "XXX", line 12, in <module>
    from spyderlib.widgets.internalshell import InternalShell
  File "spyderlib\widgets\internalshell.py", line 42, in <module>
    import spyderlib.spyder
  File "spyderlib\spyder.py", line 91, in <module>
    from spyderlib.plugins.console import Console
  File "spyderlib\plugins\console.py", line 32, in <module>
    from spyderlib.widgets.internalshell import InternalShell
ImportError: cannot import name InternalShell