Improve Spyder bootstrap time from ~2.445 to ~1.5362 seconds when --versions argument is used
get_versions(): do not import own module, use subpackages directly,
to avoid "AttributeError: 'module' object has no attribute 'qt'"

bootstrap.py: remove ugly "from spyderlib import spyder" hack that
was needed to read versions without AttributeError above