pyside: Fix renaming of tabs in IPython console
The error can be triggred by attempting to rename a tab¹ in the IPython
console (and possibly other places):

TypeError: 'PySide2.QtWidgets.QWidget.setFocus' called with wrong argument types:
  PySide2.QtWidgets.QWidget.setFocus(bool)
Supported signatures:
  PySide2.QtWidgets.QWidget.setFocus()
  PySide2.QtWidgets.QWidget.setFocus(PySide2.QtCore.Qt.FocusReason)

¹ This option is available in the right-click menu of a tab