Executing script in current Python/IPython interpreter while no interpreter is running was raising a TypeError exception:
Traceback (most recent call last):
  File "[...]\spyderlib\plugins\externalconsole.py", line 722, in run_script_in_current_shell
    "and try again.") % osp.basename(filename), QMessageBox.Ok)
  File "[...]\python-2.7.5.amd64\lib\ntpath.py", line 198, in basename
    return split(p)[1]
  File "[...]\python-2.7.5.amd64\lib\ntpath.py", line 173, in split
    while i and p[i-1] not in '/\\':
TypeError: 'in <string>' requires string as left operand, not QString

Update Issue 1540
Status: Fixed