setup.py: code cleaning (moved .ico files to a dedicaded folder in 'spyderlib')
Also fixing this error when building Spyder on Py3:
SyntaxError: invalid or missing encoding declaration for 'scripts\\spyder.ico'